# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-20 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_play'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='counter_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='play',
            name='logo',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='play',
            name='play_image',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
