# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-21 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20170721_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='counter_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='play',
            name='logo',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='play',
            name='play_image',
            field=models.ImageField(blank=True, upload_to='media'),
        ),
    ]
