# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-25 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20170721_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitter', models.CharField(max_length=200)),
                ('read_by', models.CharField(blank=True, max_length=200)),
                ('contact', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
