# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_players'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='read_by',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
