# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-07-27 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20170727_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
