# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 01:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20170727_1402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='play',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='play',
            name='hat_tip',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='play',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
