# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-08-21 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_play_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='logo',
            field=models.ImageField(blank=True, editable=False, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='play',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
